### ISSUE TITLE
Issue in Time Travel 

### ISSUE THREAD

**Issue by kvthr** [santoshimz/pattukunte-pattucheera#71]
When I choose a previous date to play, the images are not starting from the `Hint 1` image, the first image I see is from the number where I guessed the last time. 

**Example:**

- Suppose I am playing the `09-06-2022` game and got it right in the 3rd attempt.
- Now I choose `07-06-2022` game to play, the first image I see is the 3rd clue from that and not the 1st one.

**Comment by pavankalyan-codes** [comment]
@kvthr , Can you try to replicate this again and confirm if the issue persists?

**Comment by kvthr** [comment]
@pavankalyan-codes Yep! Looks good now!

**Comment by pavankalyan-codes** [comment]
Great! I'll merge
